find_package(MPI REQUIRED)
find_package(MFEM REQUIRED)

# PETSc -- prefer pkg-config (Debian provides petsc.pc via update-alternatives).
# The MFEM library may already be linked to PETSc; setting MFEM_USE_PETSC=1
# at compile time so its #ifdef paths are exposed to our code.
find_package(PkgConfig QUIET)
set(MONO_USE_PETSC OFF)
if(PkgConfig_FOUND)
  pkg_check_modules(PETSC PETSc)
  if(NOT PETSC_FOUND)
    pkg_check_modules(PETSC petsc)
  endif()
  if(PETSC_FOUND)
    message(STATUS "Found PETSc via pkg-config: ${PETSC_VERSION}")
    set(MONO_USE_PETSC ON)
    if(NOT TARGET PETSC::petsc)
      add_library(PETSC::petsc INTERFACE IMPORTED)
      target_include_directories(PETSC::petsc INTERFACE ${PETSC_INCLUDE_DIRS})
      target_link_libraries(PETSC::petsc INTERFACE ${PETSC_LIBRARIES})
      target_link_directories(PETSC::petsc INTERFACE ${PETSC_LIBRARY_DIRS})
      target_compile_definitions(PETSC::petsc INTERFACE MFEM_USE_PETSC=1)
    endif()
  endif()
endif()
if(NOT MONO_USE_PETSC)
  message(STATUS "PETSc not found, building Hypre-only path")
endif()
